kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
      env:
      - name: DD_COLLECT_EC2_TAGS_USE_IMDS
        value: true
  features:
    apm:
      enabled: true
    liveProcessCollection:
      enabled: true
    logCollection:
      enabled: true
    admissionController:
      enabled: true
    externalMetricsServer:
      enabled: true
    cspm:
      enabled: true
    prometheusScrape:
      enabled: true
  override:
    nodeAgent:
      containers:
        agent:
